config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get 'home/contact_us'
  get 'home/write_to_us'
  post 'home/register_customer_query'
  get 'home/show_query'

  devise_for :users

  authenticated :user do
    root to: "home#index", as: "authenticated_root"
  end

  root "home#welcome"

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :customers
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  belongs_to :category

  has_attached_file :image, styles: { medium: "300x300>", large: "700x1200>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  validates_numericality_of :phone_no, :only_integer => true, :allow_nil => true, :message => "Enter proper mobile number"

  validates_length_of :phone_no, :maximum => 10

  validates_presence_of :name, :email_id

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if params[:category].blank?
      @customers = Customer.all.order("created_at DESC")
    else
      @category_id = Category.find_by(name: params[:category]).id
      @customers = Customer.where(category_id: @category_id).order("created_at DESC")
    end
  end

  def welcome

  end

  def contact_us

  end

  def write_to_us
    @customer = Customer.new

  end

  def register_customer_query
    @customer = Customer.new(customer_params)

    if @customer.save
      redirect_to home_show_query_path(@customer), notice: "Successfully submitted"
    else
      render home_write_to_us_path, notice: "failed"
    end

  end

  def show_query
    @customer = Customer.find(params[:format])
  end

  private

  def find_customer
    @customer = Customer.find(params[:id])
  end
  # Never trust parameters from the scary internet, only allow the white list through.
  def customer_params
    params.require(:customer).permit(:name, :email_id, :phone_no, :category_id, :to_get_done, :image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.haml
.container
  %h1 Listing Customers
  %table.table.table-striped
    %thead
      %tr
        %th customer
        %th Email
        %th Phone No
        %th Category
        %th
    %tbody
      - @customers.each do |customer|
        %tr
          %td= customer.name
          %td= customer.email_id
          %td= customer.phone_no
          %td= customer.category.name
          %td= link_to 'Show', home_show_query_path(customer)

app/views/home/show_query.html.haml
.container{style: "margin-top:2%;"}
  %p
    %strong Name:
    = @customer.name

  %br/
  %p
    %strong Email Id:
    = @customer.email_id

  %br/
  %p
    %strong Mobile Number:
    = @customer.phone_no

  %br/
  %p
    %strong Query Category:
    = @customer.category.name

  %br/
  %p
    %strong Description:
    = @customer.to_get_done


  %br/
  %br/
  %br/
  = image_tag @customer.image.url(:large)
  %br/
  %br/

app/views/home/welcome.html.erb
<div style="width: 100%; height: calc(100vh - 50px); background-image: url(<%= image_path('bg2.jpg') %>);background-repeat: no-repeat;background-size: 100% 100%;">

  <div style="padding-top: 4%;">

    <img align="center" style="display: block; margin: auto;" src="<%= image_path('pic.jpg') %>" class="img-circle" alt="Imtiyaz" width="377" height="450">
  </div>
<br>
  <br>
  <p align="center" style="color: #ffffff; font-size: 1.5em;">
    A one stop solution for all kinds of RTO works <br> in Telangana and Andhra Pradesh
  </p>
<br>
  <p align="center" style="color: #ffffff; font-size: 1.3em;">
    Specialized in Sale-Rent Agreements, Sale Deeds, Will Deeds, EC, Link Documents, Market Value Estimation, Title Verification, Online Registration and many Others ....
  </p>
  <br>
  <br>
  <p align="center">
  <%= link_to "Write to Us", home_write_to_us_path, role:"button ", class: "btn btn-lg btn-primary"%>
  </p>

  <p align="center" style="color: #ffffff;position: absolute;bottom: 30px;width: 100%; font-size: 1.2em;">
    &copy; Imtiyaz Ali
  </p>


</div>

app/views/home/write_to_us.html.haml
.container{style: "margin-top:2%;background-image: url(#{image_path('bg.jpg')});background-repeat: no-repeat;background-size: 100% 100%;"}
  %div{style: "padding:10%;"}
    = simple_form_for @customer, url: home_register_customer_query_path do |f|


      .form-group
        = f.input :name, input_html: { class: 'form-control' }

      .form-group
        = f.input :email_id, input_html: { class: 'form-control' }

      .form-group
        = f.input :phone_no, input_html: { class: 'form-control' }


      .form-group
        = f.collection_select :category_id, Category.all, :id, :name, {promt: "Choose a category" }, input_html: { class: 'form-control' }

      .form-group
        = f.input :to_get_done, label: "Description", input_html: {rows:5, class: 'form-control' }

      .form-group
        = f.input :image, input_html: { class: 'form-control' }

      = f.button :submit, value: 'Submit', class: "btn btn-primary"

app/views/layouts/application.html.haml
!!! 5
%html
%head
  %title INA Associates
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags

%body

  %nav.navbar.navbar-default{style: "margin-bottom: 0px; background-color: currentcolor;"}
    .container
      / Brand and toggle get grouped for better mobile display
      .navbar-header
        %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
          %span.sr-only Toggle navigation
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        .navbar-brand= link_to "INA Associates", root_path

      .collapse.navbar-collapse

        - if user_signed_in?

          %ul.nav.navbar-nav
            %li= link_to "All", root_path
            - Category.all.each do |category|
              %li= link_to category.name, root_path(category: category.name)

          %ul.nav.navbar-nav.navbar-right
            %li= link_to "Sign Out", destroy_user_session_path, method: :delete

          %ul.nav.navbar-nav.navbar-right
            %li= link_to "Account", edit_user_registration_path



        - else
          %ul.nav.navbar-nav.navbar-left
            %li= link_to "Write to Us", home_write_to_us_path

          %ul.nav.navbar-nav.navbar-right
            %li= link_to "Admin Login", new_user_session_path

          %ul.nav.navbar-nav.navbar-right
            %li= link_to "Contact Us", home_contact_us_path


  = yield

:css

  html{
    height: 100%;
  }
  body {
    min-height: 100%;
  }
  .navbar-default .navbar-nav > li > a {
    color: #ffffff;
  }

  .navbar-default .navbar-nav > li > a:hover {
    color: #ccc;
  }